# Generated by Django 4.1.13 on 2024-05-25 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpenCourseAllotment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
